export const PLANT_TYPES = {
  "alder":  "tree",
  "ash":  "tree",
  "birch":  "tree",
  "cottonwood":  "tree",
  "elm":  "tree",
  "maple":  "tree",
  "olive":  "tree",
  "juniper":  "tree",
  "jpn_cedar_cypress":  "tree",
  "oak":  "tree",
  "pine":  "tree",
  "graminales":  "grass",
  "ragweed":  "weed",
};